apiVersion: v1
kind: Service
metadata:
  labels:
    name: rabbitmq-resolver
    tier: backend
    role: support
  name: rabbitmq-resolver
spec:
  clusterIP: None
  ports:
  - port: 5672
    name: client
    targetPort: 5672
  - port: 4369
    name: epmd
    targetPort: 4369
  - port: 25672
    name: internal
    targetPort: 25672
  selector:
    name: rabbitmq-ps